code/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'
# 各viewへのルーティング
urlpatterns = [
    # 顧客一覧画面面
    path('', views.MemberList.as_view(), name='member_list'),
    # 顧客情報詳細画面
    path('<int:pk>/', views.MemberDetail.as_view(), name='detail'),
    # 新規顧客登録画面
    path('create/', views.form, name='create'),
    # 顧客情報編集画面
    path('<int:pk>/update/', views.MemberUpdate.as_view(), name='update'),
    # 削除確認画面
    path('<int:pk>/delete/', views.MemberDelete.as_view(), name='delete'),
    #
    #path('regist/', views.MenuRegist.as_view(), name='regist'),
    # 注文登録画面
    # path('regist/', views.order_form, name='ajax_search'),
    path('regist/', views.OrderRegistList.as_view(), name='ajax_search'),
    # 非同期　会員情報取得取得
    #path('regist/search/', views.ajax_post_search, name='ajax_post_search'),
    path('regist/search', views.ajax_post_search, name='ajax_post_search'),
    #
    #path('regist/search/', views.OrderCreate.as_view(), name='ajax_post_search'),
    # 非同期 カテゴリ、商品名取得処理
    path('regist/goods/', views.ajax_get_goods, name='ajax_get_goods'),
    #
    #path('regist/create/', views.RegistOrder.as_view(), name='create_order'),
]

code/config/urls.py
from django.contrib import admin
from django.urls import include, path #追加 inculde

urlpatterns = [
    path('cms_web/', include('cms_web.urls')), #追加
    path('cms/', include('cms.urls')), #追加
    path('crud_app/', include('crud_app.urls')), #追加
    path('ajax/', include('ajax.urls')), #追加
    path('admin/', admin.site.urls),
]

code/cms/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator
from django.core.exceptions import ValidationError

def check_age(value):
    if value < 0 or value > 150:
        raise ValidationError('有効範囲は0歳から150歳です')


class Member(models.Model):

    #  性別を選択する選択肢を宣言
    GENDER_CHOICES = (
        (1, '男性'),
        (2, '女性'),
        (3, 'その他'),
    )

    # フィールドを定義します
    # verbose_name：人間に表示する名前を決める、adminサイトとかで使う
    name = models.CharField(max_length=255, verbose_name='名前', blank=True, null=True)  # max_lengthは長さの最大値
    # choicesにタプルを指定することで選択肢のエリアにできる、
    # blankやnullをOKにするかどうか

    name_read = models.CharField(max_length=255, verbose_name='フリガナ', blank=True, null=True)  # max_lengthは長さの最大値
    age = models.IntegerField(default=0, validators=[check_age])
    gender = models.IntegerField(verbose_name='性別', choices=GENDER_CHOICES, blank=True, null=True)
    birth_day = models.DateField(verbose_name='誕生日', blank=True, null=True)
    email = models.EmailField(verbose_name='メールアドレス', max_length=256, blank=True, null=True)
    telephone = models.CharField(verbose_name='電話番号', max_length=100, blank=True, null=True)
    zip_code = models.CharField(verbose_name='郵便番号', max_length=20, blank=True, null=True)
    prefectures = models.CharField(verbose_name='都道府県', max_length=20, blank=True, null=True)
    address_line1 = models.CharField(verbose_name='住所1', max_length=100, blank=True, null=True)
    address_line2 = models.CharField(verbose_name='住所2', max_length=100, blank=True, null=True)
    house = models.CharField(verbose_name='建物名', max_length=100, blank=True, null=True)
    remark = models.CharField(verbose_name='備考', max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成時間', auto_now_add=True)  # レコードが追加された時にその時間を保存します
    updated_at = models.DateTimeField(verbose_name='更新時間', auto_now=True)  # レコードが更新されたタイミングで現在時間が保存されます。
    visit_num = models.IntegerField(verbose_name='来店回数', blank=True, null=True, default=0)
    latest_visit_day = models.DateField(verbose_name=' 直近の来店日', blank=True, null=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    order_day = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.member.name + ":" + str(self.order_day)

class Drink(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    drink_name = models.CharField(verbose_name='ドリンク名', max_length=100, blank=True, null=True)
    drink_num = models.IntegerField(verbose_name='ドリンク個数', default=1, blank=True, null=True)

    def __str__(self):
        return str(self.pk) + ":" + self.drink_name

class Course(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    course_name = models.CharField(verbose_name='コース名', max_length=100, blank=True, null=True)
    course_num = models.IntegerField(verbose_name='コース個数', default=1, blank=True, null=True)

# カテゴリマスタ
class MenuCategory(models.Model):
    category_name = models.CharField('カテゴリ', max_length=255)

    def __str__(self):
        return self.category_name

class Goods(models.Model):
    category = models.ForeignKey(MenuCategory, on_delete=models.CASCADE)
    goods_name = models.CharField('商品', max_length=255)

    def __str__(self):
        return self.goods_name

code/cms/forms.py
from django import forms
from .models import Member,Drink


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
         # 1) 元から Model にある属性を hidden にしたい場合
        #widgets = {'__all__': forms.HiddenInput()}


class DrinkForm(forms.ModelForm):
    class Meta:
        model = Drink
        fields = '__all__'

code/cms/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from .models import Member,Order,Drink,Course,MenuCategory,Goods
from .forms import MemberForm,DrinkForm
import datetime
from django.http import JsonResponse

# 顧客一覧画面
class MemberList(ListView):
    context_object_name = 'members'
    template_name = 'cms/member_list.html'
    model = Member

    # カテゴリ取得
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        goods_list = Goods.objects.all()
        context['goods_list'] = goods_list
        return context

    def get_queryset(self):
        q_name = self.request.GET.get('name')
        q_name_read = self.request.GET.get('nameRead')
        q_age = self.request.GET.getlist('age')
        q_visit_num = self.request.GET.getlist('visitNum')
        q_latest_visit_day = self.request.GET.get('latestVisitDay')

        # 検索条件の場合分け
        object_list = Member.objects.all()
        # 名前、連絡先、住所、年齢
        if q_name:
            object_list = object_list.filter(Q(name__icontains=q_name))
        if q_name_read:
            object_list = object_list.filter(Q(name_read__icontains=q_name_read))
        if q_age:
            queries = [Q(age__range=(age, str(int(age)+ 9))) for age in q_age]
            query = queries.pop()
            for item in queries:

                query |= item

            object_list = object_list.filter(query)
        if q_visit_num:
            queries = [Q(visit_num=visit_num) for visit_num in q_visit_num]
            query = queries.pop()
            for item in queries:

                query |= item

            object_list = object_list.filter(query)
        if q_latest_visit_day:
            d_latst_visit_day = datetime.datetime.strptime(q_latest_visit_day, '%Y-%m-%d')
            object_list = object_list.filter(Q(latest_visit_day=d_latst_visit_day))

        return object_list

# 顧客情報詳細画面
class MemberDetail(DetailView):
    context_object_name = 'member'
    template_name = 'cms/member_detail.html'
    model = Member
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_list = Order.objects.filter(member_id=self.kwargs['pk'])
        #order_list = Drink.objects.filter(order__member_id=self.kwargs['pk'] )
        context['order_list'] = order_list
        # Orderの
        drink_list = Drink.objects.filter(order__member_id=self.kwargs['pk'])
        context['drink_list'] = drink_list
        return context

# 新規顧客登録画面
def form(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            member = form.save(commit=False)
            member.save()
            return redirect('cms:member_list')
    else:
        form = MemberForm()
    return render(request, 'cms/member_form.html' ,{'form': form})

# 顧客情報編集画面
class MemberUpdate(UpdateView):
    template_name = 'cms/member_update_form.html'
    model = Member
    fields = ['name', 'name_read', 'age']

    def get_success_url(self):
        return reverse('cms:detail', kwargs={'pk': self.object.pk})

    def get_form(self):
        form = super(MemberUpdate, self).get_form()
        form.fields['name'].label = '名前'
        form.fields['name_read'].label = 'フリガナ'
        form.fields['age'].label = '年齢'
        return form

# 削除確認画面
class MemberDelete(DeleteView):
    template_name = 'cms/member_confirm_delete.html'
    model = Member
    success_url = reverse_lazy('cms:member_list')

def createOrder(request):
    template_name = 'cms/order_regist.html'


# 注文登録画面
# def order_form(request):
#     print('start')
#     if request.method == 'POST':
#         # リクエストがPOSTの時
#         print('POST')
#         form = DrinkForm(request.POST)
#         if form.is_valid():
#             member = form.save(commit=False)
#             member.save()
#             # 登録成功したら、顧客一覧画面へ遷移
#             return redirect('cms:member_list')
#     else:
#         # POST以外の時
#         print('POST以外')
#         form = DrinkForm()
#         template_name = 'cms/menu_regist.html'
#         model = MenuCategory
#         print('get_context_data前')
#         def get_context_data(self, **kwargs):
#             print('get_context_data start')
#             context = super().get_context_data(**kwargs)
#             category_list = MenuCategory.objects.all()
#             context['category_list'] = category_list
#             print(context)
#             return context
#     print('return前')
#     return render(request, 'cms/menu_regist.html' ,{'form': form })

# 注文登録画面
class OrderRegistList(ListView):
    template_name = 'cms/menu_regist.html'
    model = MenuCategory
    print('get_context_data前')
    def get_context_data(self, **kwargs):
        print('get_context_data中')
        context = super().get_context_data(**kwargs)
        category_list = MenuCategory.objects.all()
        context['category_list'] = category_list
        print('get_context_data後')
        return context

class OrderCreate(CreateView):
    template_name = 'cms/menu_regist.html'
    model = Member
    fields = ['name', 'name_read', 'age']

# 非同期 カテゴリ、商品名取得処理
def ajax_post_search(request):
    keyword = request.GET.get('name')
    if keyword:
        member = [{"name" :member.name,"id" : member.id} for member in Member.objects.filter(name__icontains=keyword)]  # タイトルにキーワードを含む。大文字小文字の区別なし
    else:
        member = [{"name" :member.name,"id" : member.id} for member in Member.objects.all()]
    d = {
        "member": member
    }
    return JsonResponse(d)

# 非同期　会員情報取得取得
def ajax_get_goods(request):
    category_id = request.GET.get('category_id')

    if category_id:
        goods = [{"category_id" : goods.category.pk, "category_name" : goods.category.category_name, "goods_id" : goods.pk, "goods_name" : goods.goods_name}
        for goods in Goods.objects.filter(category_id=category_id)]
    d = {
        "goods": goods
    }
    return JsonResponse(d)

code/templates/cms/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    {% block css %}{% endblock css %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <header>
        <a href="{% url 'cms:member_list' %}">
            <h1>顧客管理システム</h1>
        </a>
    </header>
    <nav>
        <li class="li_1">
            <a href="{% url 'cms:create' %}"><button>顧客登録</button></a>
        </li>
        <li class="li_2">
            <a href="{% url 'cms:member_list' %}"><button>顧客一覧</button></a>
        </li>
        <li class="li_3">
            <a href="{% url 'cms:ajax_search' %}"><button>注文登録</button></a>
        </li>
    </nav>
    <main>
        {% block content %} {% endblock content %}
    </main>
</body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
{% block js %}{% endblock js %}
{% block extrajs %}{% endblock %}

</html>

code/templates/cms/member_confirm_delete.html
{% extends 'cms/base.html' %}
{% block title %}削除確認{% endblock title %}

{% block content %}

<h1>削除確認画面</h1>
<hr>
<form method="post">
    {% csrf_token %}
    <p>{{ member.name }}/{{ member.name_read }}/{{ member.age }}を削除しますか？</p>
    <input class="btn btn-danger" type="submit" value="削除する">
</form>


{% endblock content %}

code/templates/cms/member_detail.html
{% extends 'cms/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/member_detail.css' %}">
{% endblock css %}
{% block title %}顧客情報詳細{% endblock title %}

{% block content %}
<h1>顧客情報詳細画面</h1>
<hr>
<table>
    <tr id="content">
        <th id="lbl_name">名前：</th>
        <th id="lbl_name_read">フリガナ：</th>
        <th id="lbl_address">住所：</th>
        <th id="lbl_tel">TEL：</th>
        <th id="lbl_email">メールアドレス：</th>
        <th id="lbl_age">年齢：</th>
        <th id="lbl_remark">備考：</th>
        <td id="txt_name">{{ member.name }}</td>
        <td id="txt_name_read">{{ member.name_read }}</td>
        <td id="txt_address">
            {{ member.prefectures }}{{ member.address_line1 }}{{ member.address_line2 }}{{ member.house }}</td>
        <td id="txt_tel">{{ member.telephone }}</td>
        <td id="txt_email">{{ member.email }}</td>
        <td id="txt_age">{{ member.age }}歳</td>
        <td id="txt_remark">{{ member.remark }}</td>
    </tr>
</table>
<hr>
<div>
    <a class="btn btn-primary" href="{% url 'cms:update' member.pk %}">編集</a>
    <a class="btn btn-danger" href="{% url 'cms:delete' member.pk %}">削除</a>
</div>
<hr>
<h1>Menu</h1>

{% for orders in order_list %}
<div>
    <li>{{ orders.order_day }}
        <ul>
            <p>飲み物</p>
            {% for drinks in drink_list %}
            {% if orders.title == drinks.order.title %}
            <ul>{{ drinks.drink_name }}　×　{{ drinks.drink_num }}</ul>
            {% endif %}
            {% endfor %}
        </ul>

        <ul>前菜</ul>
        <ul>メイン</ul>
        <ul>デザート</ul>
    </li>
</div>
{% endfor %}
{% endblock content %}

code/templates/cms/member_form.html
{% extends 'cms/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/member_form.css' %}">
{% endblock css %}

{% block js %}
<script type="text/javascript" src="{% static 'js/member_form.js' %}"></script>
{% endblock js %}
{% block title %}顧客登録{% endblock title %}

{% block content %}

<h1>新規顧客登録画面</h1>
<hr>
<form method="post" novalidate>
    {% csrf_token %}
    <div class="content">
        <li class="li_t1">
            名前
        </li>
        <li class="li_d1">
            <input id="name" type="text" class="form-control">
        </li>
        <li class="li_t2">
            フリガナ
        </li>
        <li class="li_d2">
            <input id="name_read" type="text" class="form-control">
        </li>
        <li class="li_t3">
            性別
        </li>
        <li class="li_d3">
            <select id="ageArea" class="form-control">
                <option value="0">選択してください</option>
                <option value="1">男</option>
                <option value="2">女</option>
                <option value="3">その他</option>
            </select>
        </li>
        <li class="li_t4">
            生年月日
        </li>
        <li class="li_d4 form-inline">
            <input id="year" type="text" maxlength="4" class="form-control">年
            <input id="month" type="text" maxlength="2" class="form-control">月
            <input id="day" type="text" maxlength="2" class="form-control">日
        </li>
        <li class="li_t5">
            年齢
        </li>
        <li class="li_d5 form-inline">
            <input id="age" type="text" class="form-control">歳
        </li>
        <li class="li_t6">
            郵便番号
        </li>
        <li class="li_d6 form-inline">
            <input id="zipCode1" type="text" maxlength="3" class="form-control">-
            <input id="zipCode2" type="text" maxlength="4" class="form-control">
            <input id="searchBtn" type="button" class="btn btn-primary" value="住所検索">
        </li>
        <li class="li_ti_pre">
            都道府県
        </li>
        <li class="li_txt_pre">
            <input id="prefectures" type="text" class="form-control">
        </li>

        <li class="li_t7">
            住所1
        </li>
        <li class="li_d7">
            <input id="address1" type="text" class="form-control">
        </li>
        <li class="li_t8">
            住所2
        </li>
        <li class="li_d8">
            <input id="address2" type="text" class="form-control">
        </li>
        <li class="li_t9">
            建物名・部屋番号
        </li>
        <li class="li_d9">
            <input id="house" type="text" class="form-control">
        </li>
        <li class="li_t10">
            電話番号
        </li>
        <li class="li_d10">
            <input id="telephone" type="text" class="form-control">
        </li>
        <li class="li_t11">
            メールアドレス
        </li>
        <li class="li_d11">
            <input id="email" type="email" class="form-control">
        </li>
        <li class="li_t12">
            備考
        </li>
        <li class="li_d12">
            <input id="remark" type="text" class="form-control">
        </li>
    </div>
    <div>
        <input class="btn btn-primary" type="submit" id="button" value="登録">
    </div>
    {% for field in form %}
    {{ field.as_hidden }}
    {% endfor %}
</form>

{% endblock content %}

code/templates/cms/member_search.html
{% extends 'cms/base.html' %}
{% block title %}顧客検索{% endblock title %}
{% block content %}
<h1>注文登録画面</h1>
<hr>
{% endblock content %}

code/templates/cms/member_update_form.html
{% extends 'cms/base.html' %}
{% block title %}顧客情報編集{% endblock title %}

{% block content %}

<h1>顧客情報編集画面</h1>
<hr>
<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
</form>
{% endblock content %}

code/templates/cms/menu_regist.html
{% extends 'cms/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
<link rel="stylesheet" href="{% static 'css/menu_regist.css' %}">
{% endblock css %}
{% block js%}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.ja.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/menu_regist.js' %}"></script>
{% endblock js%}
{% block title %}顧客検索{% endblock title %}
{% block content %}
<div class="form-inline">
    <h1>注文登録画面</h1>
    <input type="button" class="btn btn-primary" value="登録" onclick="regist(this)">
</div>
<hr>
<div class="form-inline">
    <input type="button" value="会員検索" class="btn btn-info" onclick="pop(this)">
</div>
<ul id="search_member">
    <!-- Ajaxで追加される -->
</ul>
<hr>
<hr>
<div>
    <label>来店日:</label>
    <input type="text" id="visit_date">
</div>
<div>
    <label>来店人数:</label>
    <input type="text" id="visit_num">
</div>
<div>
    注文メニュー
</div>
<div>
    <label>①カテゴリ</label>
    <label>②商品</label>
    <label>③個数</label>
</div>
<div>
    <select name="category" onChange="get_goods()">
        <option value="0">選択してください</option>
        {% for category in category_list %}
        <option value="{{ category.pk }}">{{ category.category_name }}</option>
        {% endfor %}
    </select>
    <select id="goods" name="goods">
        <option value="0">選択してください</option>
        {% for good in goods %}
        <option value="{{ good.pk }}">{{ good.goods_name }}</option>
        {% endfor %}
    </select>
    <select name="num">
        <option value="0">選択してください</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
    </select>
    <input type="button" class="btn btn-success" id="add" value="追加">
</div>
<hr>
<div id="contentRegist_0" class="form-inline" hidden>
    <input type="button" id="btnEdt_0" class="btn btn-sm btn-success" value="編集">
    <input type="button" id="btnDel_0" class="btn btn-sm btn-danger" value="削除">
    <p id="category_0">1</p>
    <p id="goods_0">1</p>
    <p id="num_0">1</p>
</div>
<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
</form>
<!-- hidden -->
<table id="order_" class="tbl_regist">
    <tr>
        <td id="tdCategory_"></td>
        <td id="tdGoods_"></td>
        <td id="tdNum_"></td>
        <td>
            <input type="button" class="btn btn-sm btn-success" id="btnEdit_" value="編集">
        </td>
        <td>
            <input type="button" class="btn btn-sm btn-danger" id="btnDel_" value="削除">
        </td>
    </tr>
</table>
<!-- hidden -->
<div id="content_regist"></div>
<!-- モーダルウィンドウの中身 -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <div class="d-flex flex-column bd-highlight mb-3">
                    <h2>会員の検索</h2>
                    <form id="ajax-search-post" action="{% url 'cms:ajax_post_search' %}" method="GET">
                        <input type="text" id="id_name_search">
                        <button type="submit">検索</button>
                    </form>
                    <hr>
                    <div>
                        <ul id="member">
                            {% for member in members %}
                            <li>{{ member.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <input type="button" value="会員追加" class="btn btn-secondary" onclick="display_member()">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // 送信ボタンで呼ばれる
    $('#ajax-search-post').on('submit', e => {
        // デフォルトのイベントをキャンセルし、ページ遷移しないように!
        e.preventDefault();

        $.ajax({
            'url': '{% url "cms:ajax_post_search" %}',
            'type': 'GET',
            'data': {
                'name': $('#id_name_search').val(),
            },
            'dataType': 'json'
        }).done(response => {
            // 記事欄を真っ白にする。
            $('#member').empty();
            response.member.forEach(function (value) {
                const p = '<li>' + '<input type="checkbox" id="' + value["id"] + '" name="member_name" value="' + value["name"] + '">' + value["name"] + '</input></li>';
                $('#member').append(p);
            });

            var elem = $('#search_member').find('[id^=memberId_]');
            /** size関数を使って空判定 */
            if (elem[0]) {
                /** "空"でないときの処理 */
                response.member.forEach(function (value) {
                    //有効判断
                    elem.each(function (index, element) {
                        var id = $(element).attr("id").split('_');
                        if (id[1] == value["id"]) {
                            $("#" + value["id"]).prop('disabled', true);
                            $("#" + value["id"]).prop('checked', true);
                        }
                    });
                });
            }
        });
    });

    // プルダウンの取得　Ajax
    function get_goods() {
        $.ajax({
            'url': '{% url "cms:ajax_get_goods" %}',
            'type': 'GET',
            'data': {
                'category_id': $('[name=category]').val(),
            },
            'dataType': 'json'
        }).done(response => {
            // 選択欄を空にする。
            $('[name=goods]').empty();
            // option追加処理
            if ($('[name=category]').val() != "0") {
                response.goods.forEach(function (value) {
                    // optionの追加
                    var goods = { value: value["goods_id"], text: value["goods_name"] };
                    var elem = $('<option>', goods);  //要素を生成
                    $('#goods').append(elem);  //セレクトボックスに追加
                });
            } else {
                // optionの追加
                var goods = { value: "0", text: "選択してください" };
                var elem = $('<option>', goods);  //要素を生成
                $('#goods').append(elem);  //セレクトボックスに追加
            }
        });
    };

</script>


{% endblock %}