code/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'
# 各viewへのルーティング
urlpatterns = [
    # 顧客一覧画面面
    path('', views.MemberList.as_view(), name='member_list'),
    # 顧客情報詳細画面
    path('<int:pk>/', views.MemberDetail.as_view(), name='detail'),
    # 新規顧客登録画面
    path('create/', views.form, name='create'),
    # 顧客情報編集画面
    path('<int:pk>/update/', views.MemberUpdate.as_view(), name='update'),
    # 削除確認画面
    path('<int:pk>/delete/', views.MemberDelete.as_view(), name='delete'),
    #
    #path('regist/', views.MenuRegist.as_view(), name='regist'),
    # 注文登録画面
    # path('regist/', views.order_form, name='ajax_search'),
    path('regist/', views.OrderRegistList.as_view(), name='ajax_search'),
    # 非同期　会員情報取得取得
    #path('regist/search/', views.ajax_post_search, name='ajax_post_search'),
    path('regist/search', views.ajax_post_search, name='ajax_post_search'),
    #
    #path('regist/search/', views.OrderCreate.as_view(), name='ajax_post_search'),
    # 非同期 カテゴリ、商品名取得処理
    path('regist/goods/', views.ajax_get_goods, name='ajax_get_goods'),
    #
    #path('regist/create/', views.RegistOrder.as_view(), name='create_order'),
]

code/config/urls.py
from django.contrib import admin
from django.urls import include, path #追加 inculde

urlpatterns = [
    path('cms_web/', include('cms_web.urls')), #追加
    path('cms/', include('cms.urls')), #追加
    path('crud_app/', include('crud_app.urls')), #追加
    path('ajax/', include('ajax.urls')), #追加
    path('admin/', admin.site.urls),
]

code/crud_app/urls.py
from django.urls import path
from . import views

app_name = 'crud_app'
urlpatterns = [
    path('new/', views.new, name='new'),
    path('', views.MemberList.as_view(), name='member'),
    path('<int:pk>/', views.MemberDetail.as_view(), name='detail'),
    path('create/', views.MemberCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.MemberUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.MemberDelete.as_view(), name='delete'),
    path('search/', views.BookList.as_view(), name='book'),
]

code/crud_app/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator
from django.core.exceptions import ValidationError

def check_age(value):
    if value < 10 or value > 100:
        raise ValidationError('10〜100歳が範囲ですよ!')


class Member(models.Model):
    name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100,
                                validators=[MinLengthValidator(5, '5文字以上です！'),
                                            RegexValidator(r'^[a-zA-Z0-9]*$', '英数字のみです！')])
    age = models.IntegerField(
        default=0, validators=[check_age])

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.title

code/crud_app/forms.py
from django import forms


class UserForm(forms.Form):
    name = forms.CharField(label='名前', max_length=100)
    email = forms.EmailField(label='メール', max_length=100)

code/crud_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UserForm
from .models import Member
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from .models import Book

def index(request):
    param = {"message": "crud_appです"}
    return render(request, 'crud_app/index.html', param)


def hello(request):
    return HttpResponse("<H1>hello</H1>")

def new(request):
    params = {'name': '', 'email': '', 'form': None}
    if request.method == 'POST':
        form = UserForm(request.POST)
        params['name'] = request.POST['name']
        params['email'] = request.POST['email']
        params['form'] = form
    else:
        params['form'] = UserForm()
    return render(request, 'crud_app/new.html', params)

class MemberList(ListView):
    # context_object_name = 'member_list'
    model = Member
    # paginate_by = 3
    # queryset = Member.objects.all()
    # queryset = Member.objects.order_by('-age')
    # queryset = Member.objects.filter(age='11')

class MemberDetail(DetailView):
    template_name = 'crud_app/member_detail.html'
    model = Member

class MemberCreate(CreateView):
    template_name = 'crud_app/member_form.html'
    model = Member
    fields = ['name', 'nickname', 'age']

    def get_success_url(self):
        return reverse('crud_app:detail', kwargs={'pk': self.object.pk})

class MemberUpdate(UpdateView):
    template_name = 'crud_app/member_update_form.html'
    model = Member
    fields = ['name', 'nickname', 'age']

    def get_success_url(self):
        return reverse('crud_app:detail', kwargs={'pk': self.object.pk})

    def get_form(self):
        form = super(MemberUpdate, self).get_form()
        form.fields['name'].label = '名前'
        form.fields['nickname'].label = 'ニックネーム'
        form.fields['age'].label = '年齢'
        return form

class MemberDelete(DeleteView):
    template_name = 'crud_app/member_confirm_delete.html'
    model = Member

    success_url = reverse_lazy('crud_app:member')

class BookList(ListView):
     def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = Book.objects.filter(
                Q(title__icontains=q_word) | Q(author__icontains=q_word))
        else:
            object_list = Book.objects.all()
        return object_list

code/templates/crud_app/book_list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>ListViewサンプル</title>
</head>

<body>
    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text">
        <button type="submit">検索する</button>
    </form>

    <table border="1">
        <tr>
            <th>title</th>
            <th>author</th>
        </tr>
        {% for book in object_list %}
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
        </tr>
        {% endfor %}
    </table>

</body>

</html>

code/templates/crud_app/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>テンプレート</title>
</head>

<body>
    <h1>テンプレートサンプル</h1>
    <p>{{ message }}</p>
</body>

</html>

code/templates/crud_app/member_confirm_delete.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>DeleteViewサンプル</title>
</head>

<body>
    <h1>DeleteView削除確認画面</h1>
    <form method="post">
        {% csrf_token %}
        <p>{{ member.name }}/{{ member.nickname }}/{{ member.age }}を削除しますか？</p>
        <input type="submit" value="削除する">
    </form>
</body>

</html>

code/templates/crud_app/member_detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>DetailViewサンプル</title>
</head>

<body>
    <h1>DetailView詳細画面</h1>
    <table border="1">
        <tr>
            <th>name</th>
            <th>nickname</th>
            <th>age</th>
        </tr>
        <tr>
            <td>{{ member.name }}</td>
            <td>{{ member.nickname }}</td>
            <td>{{ member.age }}</td>
        </tr>
    </table>
</body>

</html>

code/templates/crud_app/member_form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>CreateViewサンプル</title>
</head>

<body>
    <h1>CreateView新規作成画面</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
</body>

</html>

code/templates/crud_app/member_list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>ListViewサンプル</title>
</head>

<body>
    <h1>ListView一覧画面</h1>
    <table border="1">
        <tr>
            <th>name</th>
            <th>詳細</th>
        </tr>
        {% for member in object_list %}
        <tr>
            <td>{{ member.name }}</td>
            <th><a href="{% url 'crud_app:detail' member.pk %}">詳細</a></th>
            <th><a href="{% url 'crud_app:update' member.pk %}">編集</a></th>
            <th><a href="{% url 'crud_app:delete' member.pk %}">削除</a></th>
        </tr>
        {% endfor %}
    </table>
</body>

</html>

code/templates/crud_app/member_update_form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>UpdateViewサンプル</title>
</head>

<body>
    <h1>UpdateView編集画面</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
</body>

</html>

code/templates/crud_app/new.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>フォーム</title>
</head>

<body>
    <h1>ユーザーフォーム</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">送信</button>
    </form>
    <p>{{ name }}</p>
    <p>{{ email }}</p>
</body>

</html>