code/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'
# 各viewへのルーティング
urlpatterns = [
    # 顧客一覧画面面
    path('', views.MemberList.as_view(), name='member_list'),
    # 顧客情報詳細画面
    path('<int:pk>/', views.MemberDetail.as_view(), name='detail'),
    # 新規顧客登録画面
    path('create/', views.form, name='create'),
    # 顧客情報編集画面
    path('<int:pk>/update/', views.MemberUpdate.as_view(), name='update'),
    # 削除確認画面
    path('<int:pk>/delete/', views.MemberDelete.as_view(), name='delete'),
    #
    #path('regist/', views.MenuRegist.as_view(), name='regist'),
    # 注文登録画面
    # path('regist/', views.order_form, name='ajax_search'),
    path('regist/', views.OrderRegistList.as_view(), name='ajax_search'),
    # 非同期　会員情報取得取得
    #path('regist/search/', views.ajax_post_search, name='ajax_post_search'),
    path('regist/search', views.ajax_post_search, name='ajax_post_search'),
    #
    #path('regist/search/', views.OrderCreate.as_view(), name='ajax_post_search'),
    # 非同期 カテゴリ、商品名取得処理
    path('regist/goods/', views.ajax_get_goods, name='ajax_get_goods'),
    #
    #path('regist/create/', views.RegistOrder.as_view(), name='create_order'),
]

code/cms_web/urls.py
from django.urls import path

from . import views

app_name = 'cms_web'
urlpatterns = [
    path('', views.index, name='index'),
    # path('regist/', views.regist, name='regist'),
    # path('list/', views.UserListView.as_view(), name='list'),
    path('search/', views.search, name='search'),
    path('list/<int:pk>/', views.MemberDetail.as_view(), name='detail'),
   # path('regist/', views.new, name='regist'),
    path('list/', views.list, name='list'),
]

code/config/urls.py
from django.contrib import admin
from django.urls import include, path #追加 inculde

urlpatterns = [
    path('cms_web/', include('cms_web.urls')), #追加
    path('cms/', include('cms.urls')), #追加
    path('crud_app/', include('crud_app.urls')), #追加
    path('ajax/', include('ajax.urls')), #追加
    path('admin/', admin.site.urls),
]

code/cms_web/models.py
from django.db import models


class MemberInfo(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(default=0)

    def __str__(self):
        return self.name

code/cms_web/forms.py
from django import forms
#from .models import MemberInfo

"""
class MemberForm(forms.ModelForm):
    class Meta:
        model = MemberInfo
        fields = ('name', 'age')
        labels = {
            'name': '名前',
            'age': '年齢'
        }
        help_texts = {
            'name': '名前を入力',
            'age': '年齢を入力'
        }

"""

code/cms_web/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, DetailView
from .models import MemberInfo
from django.urls import reverse
# from .forms import MemberForm

def index(request):
    return render(request, 'cms_web/index.html')

def search(request):
    return render(request, 'cms_web/search.html')

def regist(request):
    return render(request, 'cms_web/regist.html')

class RegistListView(ListView):
    model = MemberInfo
    template_name = "regist.html"

class UserListView(ListView):
    model = MemberInfo
    template_name = "cms_web/list.html"

class MemberDetail(DetailView):
    model = MemberInfo
    template_name = "cms_web/member_list.html"

"""
def new(request):
    params = {'message': '', 'form': None}
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list')
        else:
            params['message'] = '再入力して下さい'
            params['form'] = form
    else:
        params['form'] = MemberForm()
    return render(request, 'cms_web/regist.html', params)
"""

def list(request):
    data = MemberInfo.objects.all()
    params = {'message': 'メンバーの一覧', 'data': data}
    return render(request, 'cms_web/list.html', params)

code/templates/cms_web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/web_app.css' %}">
    {% block css %}{% endblock css %}
    {% block js %}{% endblock js %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <header>
        <a href="{% url 'cms_web:index' %}">
            <h1>顧客管理システム</h1>
        </a>
    </header>
    <nav>
        <li class="li_1">
            <a href="{% url 'cms_web:regist' %}"><button>顧客登録</button></a>
        </li>
        <li class="li_2">
            <a href="{% url 'cms_web:list' %}"><button>顧客一覧</button></a>
        </li>
        <li class="li_3">
            <a href="{% url 'cms_web:search' %}"><button>顧客検索</button></a>
        </li>
    </nav>
    <main>
        {% block content %} {% endblock content %}
    </main>
</body>

</html>

code/templates/cms_web/index.html
{% extends 'cms_web/base.html' %}
{% block css %}{% endblock css %}
{% block js %}{% endblock js %}
{% block title %}トップページ{% endblock title %}

{% block content %}

<p>継承テスト</p>
{% endblock content %}

code/templates/cms_web/list.html
{% extends 'cms_web/base.html' %}
{% block title %}顧客一覧{% endblock title %}

{% block content %}

<h1>Memberモデル</h1>
<p>{{ message }}</p>
<table border="1">
    <tr>
        <th>name</th>
        <th>age</th>
    </tr>
    {% for member in data %}
    <tr>
        <td>{{ member.name }}</td>
        <td>{{ member.age }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

code/templates/cms_web/member_form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>CreateViewサンプル</title>
</head>

<body>
    <h1>CreateView新規作成画面</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
</body>

</html>

code/templates/cms_web/member_list.html
{% extends 'cms_web/base.html' %}
{% block title %}顧客詳細{% endblock title %}

{% block content %}
{{userinfo.sex}}



{% endblock content %}

code/templates/cms_web/regist.html
{% extends 'cms_web/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/regist.css' %}">
{% endblock css %}
{% block js %}{% endblock js %}
{% block title %}顧客登録{% endblock title %}

{% block content %}
<h1>メンバー登録フォーム</h1>
<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">送信</button>
</form>
<p>{{ message }}</p>
{% endblock content %}

code/templates/cms_web/search.html
{% extends 'cms_web/base.html' %}
{% block css %}{% endblock css %}
{% block js %}{% endblock js %}
{% block title %}顧客検索{% endblock title %}

{% block content %}

<p>継承テスト2</p>
{% endblock content %}