code/ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('', views.PostList.as_view(), name='ajax_post_add'),
    path('add/', views.ajax_post_add, name='ajax_post_add'),
    path('search/', views.ajax_post_search, name='ajax_post_search'),
]

code/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'
# 各viewへのルーティング
urlpatterns = [
    # 顧客一覧画面面
    path('', views.MemberList.as_view(), name='member_list'),
    # 顧客情報詳細画面
    path('<int:pk>/', views.MemberDetail.as_view(), name='detail'),
    # 新規顧客登録画面
    path('create/', views.form, name='create'),
    # 顧客情報編集画面
    path('<int:pk>/update/', views.MemberUpdate.as_view(), name='update'),
    # 削除確認画面
    path('<int:pk>/delete/', views.MemberDelete.as_view(), name='delete'),
    #
    #path('regist/', views.MenuRegist.as_view(), name='regist'),
    # 注文登録画面
    # path('regist/', views.order_form, name='ajax_search'),
    path('regist/', views.OrderRegistList.as_view(), name='ajax_search'),
    # 非同期　会員情報取得取得
    #path('regist/search/', views.ajax_post_search, name='ajax_post_search'),
    path('regist/search', views.ajax_post_search, name='ajax_post_search'),
    #
    #path('regist/search/', views.OrderCreate.as_view(), name='ajax_post_search'),
    # 非同期 カテゴリ、商品名取得処理
    path('regist/goods/', views.ajax_get_goods, name='ajax_get_goods'),
    #
    #path('regist/create/', views.RegistOrder.as_view(), name='create_order'),
]

code/config/urls.py
from django.contrib import admin
from django.urls import include, path #追加 inculde

urlpatterns = [
    path('cms_web/', include('cms_web.urls')), #追加
    path('cms/', include('cms.urls')), #追加
    path('crud_app/', include('crud_app.urls')), #追加
    path('ajax/', include('ajax.urls')), #追加
    path('admin/', admin.site.urls),
]

code/ajax/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)

    def __str__(self):
        return self.title

code/ajax/views.py
from django.views import generic
from .models import Post
from django.http import JsonResponse


class PostList(generic.ListView):
    model = Post

def ajax_post_add(request):
    title = request.POST.get('title')
    post = Post.objects.create(title=title)
    d = {
        'title': post.title,
    }
    return JsonResponse(d)

def ajax_post_search(request):
    keyword = request.GET.get('title')

    # 検索キーワードがあればそれで絞り込み、なければ全ての記事
    # JSONシリアライズするには、Querysetをリストにする必要あり
    if keyword:
        title_list = [post.title for post in Post.objects.filter(title__icontains=keyword)]  # タイトルにキーワードを含む。大文字小文字の区別なし
    else:
        title_list = [post.title for post in Post.objects.all()]

    d = {
        'title_list': title_list,
    }
    return JsonResponse(d)

code/templates/ajax/base.html
<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Ajaxのれんしゅう</title>
</head>

<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
</body>

</html>

code/templates/ajax/post_list.html
{% extends 'ajax/base.html' %}

{% block content %}
<h2>記事一覧</h2>
<div id="posts">
    {% for post in post_list %}
    <p>{{ post.title }}</p>
    {% endfor %}
</div>

<hr>

<h2>記事の追加</h2>
<form id="ajax-add-post" action="{% url 'ajax:ajax_post_add' %}" method="POST">
    <input type="text" id="id_title" required>
    <button type="submit">送信</button>
    {% csrf_token %}
</form>

<h2>記事の検索</h2>
<form id="ajax-search-post" action="{% url 'ajax:ajax_post_search' %}" method="GET">
    <input type="text" id="id_title_search">
    <button type="submit">検索</button>
</form>

{% endblock %}

{% block extrajs %}
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // 送信ボタンで呼ばれる
    $('#ajax-add-post').on('submit', e => {
        // デフォルトのイベントをキャンセルし、ページ遷移しないように!
        e.preventDefault();

        $.ajax({
            'url': '{% url "ajax:ajax_post_add" %}',
            'type': 'POST',
            'data': {
                'title': $('#id_title').val(),  // 記事タイトル
            },
            'dataType': 'json'
        }).done(response => {
            // <p>はろー</p>のような要素を作成し、それを記事一覧エリアに追加し、入力欄をクリアする。
            const p = $('<p>', { text: response.title });
            $('#posts').prepend(p);
            $('#id_title').val('');
        });

    });

    // 送信ボタンで呼ばれる
    $('#ajax-search-post').on('submit', e => {
        // デフォルトのイベントをキャンセルし、ページ遷移しないように!
        e.preventDefault();

        $.ajax({
            'url': '{% url "ajax:ajax_post_search" %}',
            'type': 'GET',
            'data': {
                'title': $('#id_title_search').val(),  // 記事タイトル
            },
            'dataType': 'json'
        }).done(response => {
            // 記事欄を真っ白にする。
            $('#posts').empty();

            // タイトルの一覧を順に取り出す
            for (const title of response.title_list) {
                // <p>タイトル</p>を作成し、記事一覧に追加していく。
                const p = $('<p>', { text: title });
                $('#posts').append(p);
            }
        });
    });
</script>


{% endblock %}